spring.application.name=FilipinoRecipe
spring.data.mongodb.uri=mongodb+srv://kira-admin:<BMDv3I9NuIRdKw9t>@filipinorecipecluster.jiz3x2e.mongodb.net/?retryWrites=true&w=majority&appName=FilipinoRecipeCluster
