spring.application.name=FilipinoRecipeAPI
spring.data.mongodb.uri=${MONGODB_CONNECTION_STRING}
server.port=8080
logging.level.org.springframework.data.mongodb.core=DEBUG
jwt.secret=${JWT_SECRET_BASE64}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true